# Generated by Django 5.2 on 2025-05-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quizcontent_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcontent',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allquestions', to='quiz.quiztopic'),
        ),
    ]
