# Generated by Django 5.2 on 2025-05-22 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chattopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontent',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allmessages', to='chat.chattopic'),
        ),
    ]
