# Generated by Django 5.2 on 2025-05-22 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatcontent_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontent',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allmessages', to='chat.chattopic'),
        ),
    ]
